using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.2.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © Codai, LLC 2009")]
[assembly: AssemblyProductAttribute("S#arp Architecture Contrib (Release)")]
[assembly: AssemblyConfigurationAttribute("Release")]

