using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.9.5")]
[assembly: AssemblyFileVersionAttribute("1.9.5")]
[assembly: AssemblyInformationalVersionAttribute("1.9.5")]
[assembly: AssemblyCopyrightAttribute("Copyright © Codai, LLC 2011")]
[assembly: AssemblyCompanyAttribute("Codai, LLC")]
[assembly: AssemblyConfigurationAttribute("debug")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]

